version: '3.0.0'
skip_non_tags: true 
image: Visual Studio 2017
environment:
  my_secret:
    secure: Ua7qJynnwt4TrvwtNDFQUA== # Encriptada em https://ci.appveyor.com/tools/encrypt
branches:
  only:
  - master
configuration: Release
install:
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_REPO_TAG_NAME)
  package_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  file_version: $(APPVEYOR_REPO_TAG_NAME)
  informational_version: $(APPVEYOR_REPO_TAG_NAME)
build:
  verbosity: minimal
  project: utilzao.sln
build_script:
  - cmd: dotnet build
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt utilzao-tests\bin\Release\netcoreapp2.1\appsettings.json.enc -secret %my_secret%
  - cmd: dotnet pack
  - cmd: cd utilzao-tests
  - cmd: dotnet test --filter "TestCategory=ExtensionMethods-String|TestCategory=ExtensionMethods-Int"
artifacts:
  - path: '**\Utilzao*.nupkg'
    name: UtilzaoNuGet
deploy:
  # NuGet
  - provider: NuGet
    api_key:
      secure: 0/WZ9o7iCtXaw1wJXnF7UQfm8A1Kz3srLeCjgqL9lE9FvcB0Qtv9L33UG+E48dI0 # Encriptada em https://ci.appveyor.com/tools/encrypt
    skip_symbols: false
    artifact: UtilzaoNuGet
on_success:
  - echo Processo finalizado com sucesso!